# Generated by Django 3.2.8 on 2021-11-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_todo_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='active',
            field=models.BooleanField(),
        ),
    ]
