# Generated by Django 3.2.8 on 2021-11-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_rename_active_todo_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_active',
            new_name='active',
        ),
    ]
